# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# ^^^ Above line sets up validation in supported editors ^^^

# image will be published to ghcr.io/<user>/<name>
name: linuxyz
# description will be included in the image's metadata
description: My personal custom image. Make your own! https://blue-build.org/

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - system: /
      - 60-custom.just: /usr/share/ublue-os/just/60-custom.just

  - type: script
    snippets:
      - rpmkeys --import https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
      - printf "[gitlab.com_paulcarroty_vscodium_repo]\nname=download.vscodium.com\nbaseurl=https://download.vscodium.com/rpms/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg\nmetadata_expire=1h" | sudo tee -a /etc/yum.repos.d/vscodium.repo

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/peterwu/rendezvous/repo/fedora-%OS_VERSION%/peterwu-rendezvous-fedora-%OS_VERSION%.repo # bibata
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://copr.fedorainfracloud.org/coprs/atomic-studio-org/studio-presets/repo/fedora-%OS_VERSION%/atomic-studio-org-studio-presets-fedora-%OS_VERSION%.repo # walls
      - https://mise.jdx.dev/rpm/mise.repo
    install:
        # editors
        - micro
        - codium

        # termbling
        - kitty
        - foot
        - fish
        - starship
        - cheat
        - btop
        - fzf
        - eza
        - bat
        - zoxide
        - fastfetch
        - fortune-mod
        - cowsay
        - lolcat
        - cava
        - nmap
        - gh
        - mise
        - nodejs
        - npm
        - moby-engine
        - gcc
        
        # misc bg
        - python
        - python3-pip # gext
        - rsync
        - syncthing
        - tailscale

        # virt
        - qemu
        - libvirt
        - virt-manager
        - virt-install

        # gnome
        # - gnome-shell-extension-pop-shell
        # - xprop
        - gnome-shell-extension-blur-my-shell
        # - gnome-shell-extension-forge 
        - bibata-cursor-themes
        - studio-wallpapers-xyny
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: default-flatpaks
    user:
      install:
        - com.brave.Browser
        - com.github.GradienceTeam.Gradience
        - com.github.tchx84.Flatseal
        - hu.kramo.Cartridges
        - io.itch.itch
        # - com.valvesoftware.Steam
        # - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
        # - io.github.Foldex.AdwSteamGtk
        - com.usebottles.bottles
        - org.prismlauncher.PrismLauncher
        - fr.handbrake.ghb
        - io.mpv.Mpv
        - com.logseq.Logseq
        - md.obsidian.Obsidian
        - com.obsproject.Studio
        - com.google.AndroidStudio
        - com.jetbrains.IntelliJ-IDEA-Community
        - io.github.dweymouth.supersonic
        - io.gitlab.librewolf-community
        - nl.hjdskes.gcolor3
        - org.audacityteam.Audacity
        - org.blender.Blender
        - org.kde.kdenlive
        - org.shotcut.Shotcut
        - org.kde.krita
        - org.fedoraproject.MediaWriter
        - org.freedesktop.Piper
        - org.gnome.Loupe
        - org.gnome.World.PikaBackup
        # - org.gtk.Gtk3theme.Catppuccin-red
        - org.gtk.Gtk3theme.adw-gtk3
        - org.gtk.Gtk3theme.adw-gtk3-dark
        - org.musicbrainz.Picard
        - org.speedcrunch.SpeedCrunch
        
  - type: script
    scripts:
      - nautilus-open-any-terminal.sh
      - rounded-window-corners-reborn.sh
      # - rescrobbled.sh
      # - youtube-music-app.sh
      # - refind-catppuccin-theme.sh
      # - figma.sh

  - type: systemd
    system:
      enabled:
        - mount-on-boot.service
    user:
      enabled:
        - syncthing.service
        - foot-server.service

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
        - SpaceMono
        - IBMPlexMono
        - Iosevka
        - IosevkaTerm
      google-fonts:
        - Roboto
        - Open Sans
        - Work Sans
        - Outfit
        - Space Grotesk
        - Inter
        - Atkinson Hyperlegible
        - IBM Plex Sans

  - type: gnome-extensions
    install:
      - Vitals # https://extensions.gnome.org/extension/1460/vitals/
      - GSConnect # https://extensions.gnome.org/extension/1319/gsconnect/
      - Burn My Windows # https://extensions.gnome.org/extension/4679/burn-my-windows/
      - PaperWM # https://extensions.gnome.org/extension/6099/paperwm/
      - Gnome 4x UI Improvements # https://extensions.gnome.org/extension/4158/gnome-40-ui-improvements/
  - type: gnome-extensions
    install: 
      - panel-date-formatkeiii.github.com.v13 # https://extensions.gnome.org/extension/1462/panel-date-format/

  - type: gschema-overrides
    include:
      - zz1-linuxyz.gschema.override

  - type: bling
    install:
      - dconf-update-service

  - type: signing
