# image will be published to ghcr.io/<user>/<name>
name: linuxyz
# description will be included in the image's metadata
description: My personal uBlue image. Make your own! https://ublue.it/making-your-own/

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/peterwu/rendezvous/repo/fedora-%OS_VERSION%/peterwu-rendezvous-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      # - micro
      # - starship
        - python
        - rsync
        - syncthing
        - kitty
        - starship
        - zsh
        - fish
        - rEFInd
        - qemu
        - libvirt
        - virt-manager
        - virt-install
        - tailscale

        - pcmanfm
        - thunar
        - nemo

        # - gnome-shell-extension-pop-shell
        # - xprop
        - gnome-shell-extension-blur-my-shell
        # - gnome-shell-extension-forge 
        - python3-pip # gext
        - bibata-cursor-themes

        # - bismuth

        # - ulauncher
        # - fzf
        # - btop
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: default-flatpaks
    user:
      install:
        - com.brave.Browser
        - com.github.GradienceTeam.Gradience.Devel
        - com.github.tchx84.Flatseal
        - hu.kramo.Cartridges
        - io.itch.itch
        # - com.valvesoftware.Steam
        # - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
        # - io.github.Foldex.AdwSteamGtk
        - com.usebottles.bottles
        - org.prismlauncher.PrismLauncher
        - fr.handbrake.ghb
        - io.mpv.Mpv
        - com.logseq.Logseq
        - md.obsidian.Obsidian
        - com.obsproject.Studio
        - com.google.AndroidStudio
        - com.jetbrains.IntelliJ-IDEA-Community
        - io.github.dweymouth.supersonic
        - io.gitlab.librewolf-community
        - nl.hjdskes.gcolor3
        - org.audacityteam.Audacity
        - org.blender.Blender
        - org.kde.kdenlive
        - org.shotcut.Shotcut
        - org.kde.krita
        - org.fedoraproject.MediaWriter
        - org.freedesktop.Piper
        - org.gnome.Loupe
        - org.gnome.World.PikaBackup
        - org.gtk.Gtk3theme.Catppuccin-red
        - org.gtk.Gtk3theme.adw-gtk3
        - org.gtk.Gtk3theme.adw-gtk3-dark
        - org.musicbrainz.Picard
        - org.speedcrunch.SpeedCrunch
        
  - type: script
    scripts:
      - nautilus-open-any-terminal.sh
      # - rescrobbled.sh
      - youtube-music-app.sh
      - refind-catppuccin-theme.sh
      - signing.sh # this sets up the proper policy & signing files for signed images to work

  - type: systemd
    system:
      enabled:
        - mount-on-boot.service

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
        - SpaceMono
      google-fonts:
        - Roboto
        - Open Sans
        - Work Sans
        - Outfit
        - Space Grotesk

  - type: gschema-overrides
    include:
      - zz1-linuxyz.gschema.override

